spring:
  application:
    name: AIResumeAnalyzer

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.2

    mcp:
      client:
        request-timeout: 60s
        enabled: true
        initialized: true
        stdio:
          connections:
            docker-gateway:
              command: docker
              args: [ "mcp", "gateway", "run" ]

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.ai: DEBUG

    org.springframework.ai.mcp: DEBUG

    org.springframework.ai.openai: TRACE
